{
 "title": "hw_grafana",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPUla",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"node_exporter\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(node_load5{job=\"node_exporter\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(node_load15{job=\"node_exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Утилизация CPU для node_exporter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=~\"node_exporter\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free RAM" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total RAM" }
   ]
  }
 ]
}